apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
  - name: port-5000
    port: 5000
    targetPort: 5000
  - name: port-1935
    port: 1935
    targetPort: 1935
