apiVersion: v1
kind: ConfigMap
metadata:
  name: mid-station-config
data:
  app-config.yaml: |
    http_port: "80"
    app_port: "5000"
    rtmp_server_port: "1935"
  nginx-config.conf: |
    server {
      listen 80;
      server_name mid-station.com;

      location / {
        proxy_pass http://mid-station;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      location /rtmp {
        proxy_pass http://mid-station;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }